"""
Holds all constants for the game
"""
import arcade

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 650
GAME_TITLE = "Fiendship"
BACKGROUND_COLOR = arcade.color.BLACK
TILE_SCALING = .5
CHARACTER_SCALING = .5
PLAYER_MOVEMENT_SPEED = 10
GRAVITY = 1
PLAYER_JUMP_SPEED = 15
LEFT_VIEWPORT_MARGIN = 150
RIGHT_VIEWPORT_MARGIN = 150
BOTTOM_VIEWPORT_MARGIN = 100
TOP_VIEWPORT_MARGIN = 100


"""
    His constants :
WINDOW_WIDTH = 500
WINDOW_HEIGHT = 500
BACKGROUND_COLOR = arcade.color.BLACK
GAME_TITLE = "Introduction"
GAME_SPEED = 1/60
"""